allow-shorthand: false

pylint:
  run: false

pyroma:
  run: false

frosted:
  run: false

vulture:
  run: false

dodgy:
  run: false

pep257:
  run: false

pep8:
  options:
    max-line-length: 119

mccabe:
  options:
    max-complexity: 10
